# -*- coding: utf-8 -*-
"""Kfold&cross_fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Gpt0qoSeE3ubpoiJQUKJJRVCduSfzEY
"""

import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.3)

log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
log_reg.score(x_test, y_test)

svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

rand_for= RandomForestClassifier()
rand_for.fit(x_train, y_train)
rand_for.score(x_test, y_test)

from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

def get_score(model, x_train, y_train, x_test, y_test):
  model.fit(x_train, y_train)
  return model.score(x_test, y_test)

print(get_score(LogisticRegression(max_iter=1000), x_train, y_train, x_test, y_test))

from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

score_l=[]
score_svm=[]
score_rf=[]
for train_index,test_index in kf.split(digits.data):
    x_train_fold, x_test_fold, y_train_fold, y_test_fold = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(max_iter=1000), x_train_fold, y_train_fold, x_test_fold, y_test_fold))
    score_svm.append(get_score(SVC(), x_train_fold, y_train_fold, x_test_fold, y_test_fold))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train_fold, y_train_fold, x_test_fold, y_test_fold))
print("Logistic Regression Scores:", score_l)
print("SVM Scores:", score_svm)
print("Random Forest Scores:", score_rf)

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), digits.data, digits.target)

cross_val_score(SVC(), digits.data, digits.target)

cross_val_score(RandomForestClassifier(), digits.data, digits.target)